### ISSUE TITLE
modulenotfounderror

### ISSUE THREAD

**Issue by xAtsuUC** [Chatic-Gaming/DiscordSelfbot#2]
>python selfbot.py
Traceback (most recent call last):
  File "selfbot.py", line 21, in <module>
    import inputimeout
ModuleNotFoundError: No module named 'inputimeout'

**Comment by Chatic-Gaming** [comment]
Have you tried using pip to install?
``pip install inputimout``

**Comment by TiziFioretti** [comment]
umm no, i just delete
import inputimeout
from inputimeout import inputimeout, TimeoutOccurred
and now its working, but thanks!
